version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: blog_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: blog
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: blog_user
      DB_PASSWORD: blog_password
      DB_NAME: blog
    depends_on:
      - mysql
    networks:
      - frontend-network
      - backend-network

  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - frontend-network

volumes:
  mysql-data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
