name: backend
on:
  push:
    branches:
      - ci-cd
    # paths:
    #   - 'backend/**'   # バックエンドのコードが変更されたとき
  pull_request:
    branches:
      - ci-cd
    # paths:
    #   - 'backend/**'   # バックエンドのコードが変更されたとき

jobs:
  # バックエンドのテスト
  backend-test:
    # if: github.event_name == 'push' && contains(github.event.head_commit.message, 'backend') || contains(github.event.pull_request.head.ref, 'backend') || github.event.pull_request != '' && contains(github.event.pull_request.base.ref, 'main')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache-dependency-path: backend/go.sum
      - name: Install dependencies
        working-directory: ./backend # ワーキングディレクトリを./backendに変更
        run: go mod download
      - name: Build
        working-directory: ./backend # ワーキングディレクトリを./backendに変更
        run: go build -v ./...
      - name: Test with the Go CLI
        working-directory: ./backend # ワーキングディレクトリを./backendに変更
        run: go test ./...
