name: CI Pipeline

on:
  push:
    branches:
      - ci-cd
    # paths:
    #   - 'frontend/**'  # フロントエンドのコードが変更されたとき
    #   - 'backend/**'   # バックエンドのコードが変更されたとき
  pull_request:
    branches:
      - ci-cd
    # paths:
    #   - 'frontend/**'  # フロントエンドのコードが変更されたとき
    #   - 'backend/**'   # バックエンドのコードが変更されたとき

jobs:
  # # フロントエンドのテスト
  # frontend-test:
  #   if: github.event_name == 'push' && contains(github.event.head_commit.message, 'frontend') || contains(github.event.pull_request.head.ref, 'frontend') || github.event.pull_request != '' && contains(github.event.pull_request.base.ref, 'main')
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Set up Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: 18

  #   - name: Install dependencies
  #     run: npm install

  #   - name: Run tests
  #     run: npm test

  # バックエンドのテスト
  backend-test:
    # if: github.event_name == 'push' && contains(github.event.head_commit.message, 'backend') || contains(github.event.pull_request.head.ref, 'backend') || github.event.pull_request != '' && contains(github.event.pull_request.base.ref, 'main')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
